create table `BUCKET_METADATA` (
  `ID` VARCHAR(36) NOT NULL,
  `NAME` VARCHAR(40) NOT NULL,
  `DESCRIPTION` VARCHAR(100),
  `INFLUX_ID` VARCHAR(36) NOT NULL,
  `RETENTION_PERIOD` INT NOT NULL,
  `DATE_CREATED` DATETIME,
  `DATE_MODIFIED` DATETIME,
  `USER_ID` VARCHAR(36) NOT NULL,
  CONSTRAINT `BMD_PK`
    PRIMARY KEY (`ID`),
  CONSTRAINT `BMD_USERS_FK`
    FOREIGN KEY(`USER_ID`)
    REFERENCES `USERS` (`ID`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT
) ENGINE = InnoDB;

create table `TIMESERIES_METADATA` (
  `ID` VARCHAR(36) NOT NULL,
  `NAME` VARCHAR(40) NOT NULL,
  `DESCRIPTION` VARCHAR(1000),
  `TYPE` VARCHAR(40) NOT NULL,
  `INFLUX_ID` VARCHAR(36) NOT NULL,
  `DATE_CREATED` DATETIME,
  `DATE_MODIFIED` DATETIME,
  `BUCKET_ID` VARCHAR(36) NOT NULL,
  `ROWS_COUNT` INT,
  `COLUMNS_COUNT` INT,
  `COLUMNS` JSON,
  `TAGS` JSON,
  CONSTRAINT `TSMD_PK`
    PRIMARY KEY (`ID`),
  CONSTRAINT `TSMD_BUCKETS_FK`
    FOREIGN KEY(`BUCKET_ID`)
    REFERENCES `BUCKET_METADATA` (`ID`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT
) ENGINE = InnoDB;
