CREATE TABLE `sdliticadb`.`USERS` (
  `ID` VARCHAR(36) NOT NULL,
  `FIRST_NAME` VARCHAR(45) NULL,
  `LAST_NAME` VARCHAR(45) NULL,
  `EMAIL` VARCHAR(45) NOT NULL,
  `PASSWORD` VARCHAR(256) NOT NULL,
  CONSTRAINT `USERS_PK`
    PRIMARY KEY (`ID`),
  UNIQUE INDEX `USERS_ID_UI` (`ID` ASC) VISIBLE,
  UNIQUE INDEX `USERS_EMAIL_UI` (`EMAIL` ASC) VISIBLE)
ENGINE = InnoDB;


CREATE TABLE `sdliticadb`.`USER_TOKENS` (
  `ID` VARCHAR(36) NOT NULL,
  `TOKEN` VARCHAR(256) NULL,
  `USER_ID` VARCHAR(36) NOT NULL,
  `EXPIRATION` DATETIME NOT NULL,
  CONSTRAINT `USER_TOKENS_PK`
    PRIMARY KEY (`ID`),
  UNIQUE INDEX `USER_TOKENS_UI` (`ID` ASC) VISIBLE,
  INDEX `USER_TOKEN_USER_FK_I` (`USER_ID` ASC) VISIBLE,
  CONSTRAINT `USER_TOKEN_USER_FK`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `sdliticadb`.`USERS` (`ID`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT);
