CREATE TABLE `sdliticadb`.`ANALYTICS_MODULES` (
  `ID` VARCHAR(36) NOT NULL,
  `QUEUE_NAME` VARCHAR(40) NOT NULL,
  `LAST_HEARD_TIME` DATETIME,
  CONSTRAINT `ANALYTICS_MODULES_PK`
    PRIMARY KEY(`ID`)
) ENGINE = InnoDB;

CREATE TABLE `sdliticadb`.`ANALYTICS_OPERATIONS` (
  `ID` VARCHAR(36) NOT NULL,
  `NAME` VARCHAR(40) NOT NULL UNIQUE,
  `DESCRIPTION` VARCHAR(40),
  CONSTRAINT `ANALYTICS_OPERATIONS_PK`
    PRIMARY KEY(`ID`)
) ENGINE = InnoDB;

CREATE TABLE `sdliticadb`.`ANALYTICS_MODULES_OPERATIONS` (
  `ID` VARCHAR(36) NOT NULL,
  `ANALYTICS_OPERATION_ID` VARCHAR(36) NOT NULL,
  `ANALYTICS_MODULE_ID` VARCHAR(36) NOT NULL,
  CONSTRAINT `MODULESOPERATIONS_PK`
    PRIMARY KEY(`ID`),
  CONSTRAINT `MODULESOPERATIONS_OPERATIONS_FK`
    FOREIGN KEY (`ANALYTICS_OPERATION_ID`)
    REFERENCES `sdliticadb`.`ANALYTICS_OPERATIONS` (`ID`)
    ON DELETE CASCADE,
  CONSTRAINT `MODULESOPERATIONS_MODULES_FK`
    FOREIGN KEY (`ANALYTICS_MODULE_ID`)
    REFERENCES `sdliticadb`.`ANALYTICS_MODULES` (`ID`)
    ON DELETE CASCADE
) ENGINE = InnoDB;

CREATE TABLE `sdliticadb`.`USER_ANALYTICS_OPERATIONS` (
  `ID` VARCHAR(36) NOT NULL,
  `OPERATION_NAME` VARCHAR(40) NOT NULL/* later will change to ANALYTICS_OPERATIONS_ID fk */,
  `TIMESERIES_EXTERNAL_ID` VARCHAR(36) NOT NULL,/* later will change to TIMESERIES_METADATA_ID fk */
  `STATUS` TINYINT,
  `RESULT_LOCATION` VARCHAR(80),
  CONSTRAINT `USER_ANALYTICS_OPERATION_PK`
    PRIMARY KEY(`ID`)
) ENGINE = InnoDB;
