CREATE TABLE `sdliticadb`.`USER_API_KEYS` (
  `ID` VARCHAR(36) NOT NULL,
  `USER_ID` VARCHAR(40) NOT NULL,
  `API_KEY` VARCHAR(256) NULL,
  CONSTRAINT `USER_API_KEYS_PK`
    PRIMARY KEY(`ID`),
  CONSTRAINT `USER_API_KEYS_USER_FK`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `sdliticadb`.`USERS` (`ID`)
    ON DELETE CASCADE
) ENGINE = InnoDB;
